- hosts: localhost
  name: Volume_Create
  gather_facts: false
  vars:
    hostname:
    volname:
    vserver:
    aggrname:
    size:
    aggr:
    e_policy: 
    qos_policy:
    export_policy:
    state: present
  tasks:
  - name: "{{ tower_job_template_name }}"
    netapp.ontap.na_ontap_volume:
      state: "{{ state }}"
      name: "{{ volname }}"
      aggregate_name: "{{ aggrname }}"
      size: "{{ size }}"
      size_unit: gb
      policy: "{{ export_policy }}"
      junction_path: "/{{ volname }}"
      space_guarantee: "none"
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
      efficiency_policy: "{{ e_policy }}"
      qos_policy_group: "{{ qos_policy }}"